server:
  servlet:
    context-path: /booksmanager
spring:
  profiles:
    active: dev #  这里可以改成dev或test或prod来激活不同的配置文件
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
# Mybatis配置
mybatis:
  # 配置XML映射文件中指定的实体类别名路径
  type-aliases-package: com.example.demo.model
  # 配置MyBatis的xml配置文件路径
  mapper-locations: classpath:mapper/*.xml
  # 开启驼峰
  map-underscore-to-camel-case: true

